# Generated by Django 3.0.2 on 2020-01-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('real_url', models.TextField()),
                ('url', models.CharField(max_length=6, unique=True)),
                ('created_by', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrlStatistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clicked_by', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shortening.ShortUrl')),
            ],
        ),
    ]
