# Generated by Django 3.0.2 on 2020-01-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlstatistic',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortening.ShortUrl'),
        ),
    ]
